import jquery from "jquery";
window.jQuery = jquery;
window.$ = jquery;
import popper from "popper.js";
window.Popper = popper;
import "bootstrap";
import "metismenu";
import "axios";
import _ from "lodash";
window._ = _;
import "moment";
import swal from "sweetalert2";
window.swal = swal;
import Cookies from "js-cookie";
window.Cookies = Cookies;
import "toastr";
